### ISSUE TITLE
cpan?

### ISSUE THREAD

**Issue by djzort** [shoichikaji/HTTP-Tiny-Bandwidth#1]
hi there, will you be pushing this to cpan?

**Comment by skaji** [comment]
Thanks! I will, probably this weekend.

**Comment by djzort** [comment]
terriffic, i am looking forward to using it

**Comment by skaji** [comment]
sorry it took so long, I've just released it.
https://metacpan.org/release/SKAJI/HTTP-Tiny-Bandwidth-0.01

**Comment by djzort** [comment]
thanks!!1
